// app/constants/strings.ts
/**
 * Centralized Spanish (es-MX) UI strings. Single place to edit copy; if real
 * i18n is ever needed, this becomes the default locale file. Not auto-imported
 * — import explicitly: `import { S } from '~/constants/strings'`.
 */
export const S = {
  app: {
    name: 'Gestor de Contratos',
    shortName: 'Contratos',
  },
  common: {
    save: 'Guardar',
    send: 'Enviar',
    saveAndSend: 'Guardar y enviar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    back: 'Regresar',
    loading: 'Cargando…',
    search: 'Buscar',
    empty: 'Sin información',
    error: 'Ocurrió un error',
  },
  login: {
    title: 'Iniciar sesión',
    subtitle: 'Ingresa con tu usuario y contraseña',
    username: 'Usuario',
    password: 'Contraseña',
    submit: 'Entrar',
    usernameRequired: 'Ingresa tu usuario',
    passwordRequired: 'Ingresa tu contraseña',
    invalidCredentials: 'Usuario o contraseña incorrectos',
  },
  nav: {
    myContracts: 'Mis contratos',
    users: 'Usuarios',
    dashboard: 'Tablero',
    logbook: 'Bitácora',
    estimates: 'Estimaciones',
    schedule: 'Programa de obra',
    financial: 'Financiero',
    concepts: 'Catálogo de conceptos',
    evidence: 'Evidencias',
    files: 'Archivos',
    contract: 'Contrato',
    logout: 'Cerrar sesión',
  },
  roles: {
    admin: 'Administrador',
    resident: 'Residente',
    superintendent: 'Superintendente',
    supervisor: 'Supervisor',
    financial: 'Finanzas',
  },
  estimateStatus: {
    draft: 'Borrador',
    submitted: 'Enviada',
    with_notes: 'Con notas',
    rejected: 'Rechazada',
    approved: 'Aprobada',
    paid: 'Pagada',
  },
  agreementStatus: {
    draft: 'Borrador',
    submitted: 'Enviado',
    with_notes: 'Con notas',
    rejected: 'Rechazado',
    pending_entity: 'Pendiente de aprobación de entidad',
    approved: 'Aprobado',
  },
  contractStatus: {
    active: 'Activo',
    closing: 'En cierre',
    closed: 'Cerrado',
  },
  dashboard: {
    title: 'Mis contratos',
    newContract: 'Nuevo contrato',
    empty: 'No tienes contratos asignados.',
    physicalProgress: 'Avance físico',
    executed: 'Ejercido',
    contracted: 'Contratado',
    alerts: 'Tienes alertas en este contrato',
  },
  contractDashboard: {
    balance: 'Balance',
    anticipo: 'Anticipo',
    overSchedule: 'Avance vs programa',
    programmed: 'Programado',
    actual: 'Real',
    physical: 'Físico',
    financial: 'Financiero',
    recentLogbook: 'Bitácora reciente',
    recentEstimates: 'Estimaciones recientes',
    viewAll: 'Ver todo',
    folio: 'Folio',
    noLogNotes: 'Sin notas de bitácora',
    noEstimates: 'Sin estimaciones',
    legend: 'Estados',
  },
  actions: {
    newLogNote: 'Nueva nota',
    uploadEvidence: 'Subir evidencia',
    conceptCatalog: 'Catálogo de conceptos',
    schedule: 'Programa de obra',
    files: 'Archivos',
  },
  conceptCatalog: {
    title: 'Catálogo de conceptos',
    empty: 'Este contrato no tiene conceptos registrados.',
    readonlyNotice: 'El catálogo es de solo lectura. Para modificar conceptos inicia un convenio modificatorio.',
    newAgreement: 'Nuevo convenio',
    columns: {
      specification: 'Especificación',
      description: 'Descripción',
      unit: 'Unidad',
      unitPrice: 'P.U.',
      contractedQty: 'Vol. contratado',
      contractedAmount: 'Importe contratado',
      executed: 'Vol. ejecutado',
      executedAmount: 'Importe ejecutado',
      remaining: 'Vol. por ejecutar',
    },
    search: 'Buscar concepto…',
    total: 'Total contratado',
  },
  estimateForm: {
    title: 'Nueva estimación',
    editTitle: 'Editar estimación',
    saveDraft: 'Guardar borrador',
    submit: 'Enviar a revisión',
    deleteDraft: 'Eliminar borrador',
    deleteConfirm: '¿Eliminar este borrador? Esta acción no se puede deshacer.',
    steps: {
      period: 'Período',
      hojas: 'Hojas generadoras',
      review: 'Revisión',
    },
    period: {
      title: 'Selecciona el período',
      selector: 'Período de esta estimación',
      dates: 'Fechas del período',
      noPeriods: 'No hay períodos disponibles.',
      helper: 'Una vez seleccionado el período, guarda el borrador para comenzar a agregar Hojas Generadoras.',
    },
    hojas: {
      title: 'Hojas generadoras',
      empty: 'Aún no has agregado Hojas Generadoras.',
      add: 'Agregar Hoja Generadora',
      pickConcept: 'Selecciona un concepto',
      noConceptsForPeriod: 'No hay conceptos programados para este período.',
      alreadyAdded: 'Este concepto ya tiene una Hoja.',
      number: 'No. de Hoja Generadora',
      estimateNo: 'Estimación No.',
      period: 'Período de Ejecución',
      contractNo: 'No. Contrato',
      workDescription: 'Descripción de la Obra o Servicio',
      partida: 'Partida',
      clave: 'Clave',
      catalogo: 'Catálogo',
      ejecutado: 'Ejecutado en el Período',
      documento: 'Documento',
      unidad: 'Unidad',
      cantidad: 'Cantidad',
      total: 'Total',
      addRow: 'Agregar renglón',
      removeRow: 'Quitar renglón',
      removeHoja: 'Quitar Hoja',
      rowPhoto: 'Fotografía',
      rowPhotoRequired: 'Requerida para enviar',
      pickPhoto: 'Seleccionar del explorador',
      uploadPhoto: 'Subir foto',
      addFiles: 'Archivos adicionales',
      linkLogNotes: 'Notas de bitácora',
      hojaTotal: 'Total de la Hoja',
    },
    review: {
      title: 'Revisión',
      hint: 'Revisa las tres secciones antes de enviar. Los totales se calculan a partir de las Hojas Generadoras.',
    },
    validation: {
      periodRequired: 'Selecciona un período.',
      noHojas: 'Agrega al menos una Hoja Generadora.',
      photoRequired: 'Cada renglón requiere una fotografía para poder enviar.',
    },
  },
  estimateDoc: {
    // Cover
    coverTitle: 'Carátula de Estimación',
    workDescription: 'Descripción de la obra o servicio',
    contractNumber: 'Número del contrato',
    contractDate: 'Fecha del contrato',
    razonSocial: 'Razón Social',
    rfc: 'Registro Federal de Contribuyentes (RFC)',
    number: 'Número',
    period: 'Período',
    currentDate: 'Fecha',
    // Cover table 1
    sinIvaTitle: 'Importes sin incluir IVA',
    importe: 'Importe',
    porcentaje: 'Porcentaje',
    importeContrato: 'Importe del contrato',
    importeEstAcumAnterior: 'Importe Estimado Acumulado Anterior',
    importeEstActual: 'Importe de la Estimación Actual',
    importeEstAcumActual: 'Importe Estimado Acumulado Actual',
    saldoPorEstimar: 'Saldo por Estimar',
    // Cover table 2
    delAnticipoTitle: 'Del Anticipo',
    importeAnticipo: 'Importe del Anticipo',
    importeAmortAcumAnterior: 'Importe Amortizado Acumulado Anterior',
    importeAmortActual: 'Importe de la Amortización Actual',
    importeAmortAcumActual: 'Importe Amortizado Acumulado Actual',
    saldoPorAmortizar: 'Saldo por Amortizar',
    // Cover table 3
    netoTitle: 'Del Neto a Recibir',
    importeEstimacion: 'Importe de Estimación',
    ivaEstimacion: 'IVA Estimación',
    totalEstimacion: 'Total Estimación',
    amortizacionAnticipo: 'Amortización Anticipo',
    ivaAmortizacion: 'IVA Amortización Anticipo',
    totalAmortizacion: 'Total Amortización',
    retenciones: 'Retenciones',
    cincoAlMillar: '5 al Millar SFP (.5%)',
    totalNeto: 'Total Neto al Pagar',
    // Services section
    servicesTitle: 'Estimación de Servicios Ejecutados',
    conceptoNum: 'Concepto Num.',
    especificacion: 'Especificación Núm.',
    conceptoObra: 'Concepto de Obra',
    cantidadesObra: 'Cantidades de Obra',
    unidad: 'Unidad',
    segunProyecto: 'Según Proyecto',
    hastaAnterior: 'Hasta Estimación Anterior',
    deEsta: 'De Esta Estimación',
    totalEstimado: 'Total Estimado',
    porEjecutar: 'Por Ejecutar',
    precioUnitario: 'Precio Unitario',
    total: 'Total',
    // Summary section
    summaryTitle: 'Resumen por Partida',
    numPartida: 'Num. de Partida',
    descripcion: 'Descripción',
    subtotal: 'Subtotal',
    // Section notes banner
    sectionNote: 'Nota del supervisor',
  },
  estimateDetail: {
    titlePrefix: 'Estimación',
    period: 'Periodo',
    review: { title: 'Revisión' },
    sections: {
      signatures: 'Firmas',
      history: 'Historial',
    },
    signatures: {
      signed: 'Firmada',
      pending: 'Pendiente',
      signedAt: 'Firmó',
      unsigned: 'Sin firmar',
    },
    actions: {
      submit: 'Enviar a revisión',
      returnWithNotes: 'Devolver con notas',
      reject: 'Rechazar',
      markPaid: 'Marcar como pagada',
      sign: 'Firmar y aprobar',
      newForPeriod: 'Nueva estimación para el período',
    },
    note: {
      returnTitle: 'Devolver con notas',
      rejectTitle: 'Rechazar estimación',
      label: 'Motivo',
      placeholder: 'Describe el motivo…',
      required: 'Escribe el motivo.',
      perSectionHint: 'Agrega una nota por sección. Todas son opcionales.',
      cover: 'Nota — Carátula',
      services: 'Nota — Servicios Ejecutados',
      summary: 'Nota — Resumen por Partida',
      hoja: 'Nota — Hoja',
    },
    banner: {
      withNotes: 'Devuelta con notas',
      rejected: 'Rechazada',
      notEditable: 'Las estimaciones devueltas o rechazadas no se pueden editar. Crea una nueva estimación para este período.',
    },
  },
  workflow: {
    created: 'Creada',
    submitted: 'Enviada a revisión',
    returned_with_notes: 'Devuelta con notas',
    rejected: 'Rechazada',
    pending_entity: 'Pendiente de aprobación de entidad',
    entity_approved: 'Aprobada por la entidad',
    approved: 'Aprobada',
    paid: 'Pagada',
    signed: 'Firmada',
    reopened: 'Reabierta',
  },
  contractInfo: {
    title: 'Información del contrato',
    sections: {
      general: 'Datos generales',
      parties: 'Partes',
      agreements: 'Convenios modificatorios',
      closing: 'Cierre del contrato',
    },
    fields: {
      code: 'Clave / licitación',
      title: 'Objeto del contrato',
      status: 'Estado',
      amount: 'Monto contratado',
      anticipo: 'Porcentaje de anticipo',
      startDate: 'Fecha de inicio',
      endDate: 'Fecha de terminación',
      entity: 'Entidad',
      resident: 'Residente',
      superintendent: 'Superintendente',
      supervisor: 'Supervisor',
      contractor: 'Empresa contratista',
      supervisorCorporation: 'Empresa supervisora',
    },
    agreements: {
      empty: 'Sin convenios modificatorios.',
      new: 'Nuevo convenio',
      number: 'Convenio No.',
      kindLabel: { amount: 'Monto', time: 'Plazo', mixed: 'Mixto' },
    },
    closing: {
      reception: 'Acta de recepción',
      finiquito: 'Finiquito',
      notStarted: 'No iniciado',
      initiate: 'Iniciar',
      view: 'Ver',
      finiquitoBlocked: 'Disponible una vez aprobada el acta de recepción',
    },
  },
  agreement: {
    titlePrefix: 'Convenio',
    newTitle: 'Nuevo convenio modificatorio',
    editTitlePrefix: 'Editar convenio',
    kind: { amount: 'Modificación de monto', time: 'Modificación de plazo', mixed: 'Modificación mixta' },
    fields: {
      description: 'Descripción del convenio',
      descriptionPlaceholder: 'Describe el alcance del convenio modificatorio…',
      amountDelta: 'Variación de monto (MXN)',
      amountDeltaHint: 'Positivo = ampliación, negativo = reducción. Deja en blanco si no aplica.',
      timeDeltaDays: 'Variación de plazo (días)',
      timeDeltaHint: 'Positivo = ampliación, negativo = reducción. Deja en blanco si no aplica.',
    },
    saveDraft: 'Guardar borrador',
    saveChanges: 'Guardar cambios',
    actions: {
      submit: 'Enviar a firma',
      sign: 'Firmar',
      approve: 'Aprobar convenio',
      returnWithNotes: 'Devolver con notas',
      reject: 'Rechazar',
      edit: 'Editar',
    },
    note: {
      returnTitle: 'Devolver con notas',
      rejectTitle: 'Rechazar convenio',
      label: 'Motivo',
      placeholder: 'Describe el motivo…',
      required: 'Escribe el motivo.',
    },
    banner: { withNotes: 'Devuelto con notas', rejected: 'Rechazado' },
    sections: { detail: 'Detalle', signatures: 'Firmas', history: 'Historial' },
    effectNotice: 'Al aprobarse, la variación de plazo se aplica a la fecha de término. El monto lo recalcula el sistema.',
    conceptChanges: {
      title: 'Cambios a conceptos existentes',
      hint: 'Selecciona conceptos del catálogo y modifica los campos que cambien en este convenio.',
      addConcept: 'Agregar concepto',
      empty: 'Sin conceptos modificados.',
      columns: {
        specification: 'Especificación',
        description: 'Descripción',
        currentQty: 'Vol. actual',
        newQty: 'Nuevo vol.',
        currentPrice: 'P.U. actual',
        newPrice: 'Nuevo P.U.',
        currentStart: 'Inicio actual',
        newStart: 'Nuevo inicio',
        currentEnd: 'Término actual',
        newEnd: 'Nuevo término',
        remove: 'Quitar',
      },
    },
    newConcepts: {
      title: 'Conceptos nuevos',
      hint: 'Estos conceptos se agregarán al catálogo al aprobarse el convenio.',
      add: 'Agregar concepto nuevo',
      empty: 'Sin conceptos nuevos.',
      columns: {
        specification: 'Especificación',
        description: 'Descripción',
        unit: 'Unidad',
        qty: 'Vol.',
        unitPrice: 'P.U.',
        remove: 'Quitar',
      },
      validation: {
        specRequired: 'Especificación requerida',
        descRequired: 'Descripción requerida',
        unitRequired: 'Unidad requerida',
        qtyRequired: 'Vol. debe ser mayor a 0',
        priceRequired: 'P.U. debe ser mayor a 0',
      },
    },
    summary: {
      derivedAmountDelta: 'Variación neta de monto',
      derivedTimeDelta: 'Variación de plazo',
      days: 'días',
      noChanges: 'Sin cambios de monto registrados.',
    },
    validation: {
      descriptionRequired: 'Escribe la descripción del convenio.',
      noChanges: 'Agrega al menos un cambio a un concepto, concepto nuevo, sección nueva o cambio de fechas.',
    },
    contractDates: {
      title: 'Cambio de fechas del contrato',
      newStart: 'Nueva fecha de inicio',
      newEnd: 'Nueva fecha de término',
      current: 'Actual',
    },
  },
  reception: {
    title: 'Acta de recepción',
    initiate: 'Iniciar acta de recepción',
    logNoteStep: {
      title: 'Nota de bitácora de cierre',
      hint: 'Esta nota quedará vinculada automáticamente al acta de recepción.',
      titleLabel: 'Título',
      titlePlaceholder: 'Ej. Acta de entrega-recepción de obra',
      bodyLabel: 'Descripción',
      bodyPlaceholder: 'Describe el estado de la obra al momento de la recepción…',
      dateLabel: 'Fecha',
      required: 'Este campo es requerido.',
      create: 'Crear nota y continuar',
    },
    actions: {
      submit: 'Enviar a firma',
      sign: 'Firmar y aprobar',
      returnWithNotes: 'Devolver con notas',
      reject: 'Rechazar',
    },
    note: {
      returnTitle: 'Devolver con notas',
      rejectTitle: 'Rechazar acta',
      label: 'Motivo',
      placeholder: 'Describe el motivo…',
      required: 'Escribe el motivo.',
    },
    banner: { withNotes: 'Devuelta con notas', rejected: 'Rechazada' },
    linkedLogNote: 'Nota de bitácora vinculada',
    sections: { signatures: 'Firmas', history: 'Historial' },
  },
  finiquito: {
    title: 'Finiquito',
    initiate: 'Iniciar finiquito',
    blockedNotice: 'El finiquito solo puede iniciarse una vez que el acta de recepción esté aprobada.',
    actions: {
      submit: 'Enviar a firma',
      sign: 'Firmar y aprobar',
      returnWithNotes: 'Devolver con notas',
      reject: 'Rechazar',
    },
    note: {
      returnTitle: 'Devolver con notas',
      rejectTitle: 'Rechazar finiquito',
      label: 'Motivo',
      placeholder: 'Describe el motivo…',
      required: 'Escribe el motivo.',
    },
    banner: { withNotes: 'Devuelto con notas', rejected: 'Rechazado' },
    sections: { signatures: 'Firmas', history: 'Historial' },
  },
  newContract: {
    title: 'Nuevo contrato',
    sections: {
      general: 'Datos generales',
      rates: 'Tasas y retenciones',
      parties: 'Partes del contrato',
      concepts: 'Catálogo de conceptos',
      schedule: 'Programa de obra',
    },
    fields: {
      code: 'Clave / licitación',
      codePlaceholder: 'Ej. LPI-SRO-2025-001',
      title: 'Objeto del contrato',
      titlePlaceholder: 'Describe el objeto de la obra o servicio…',
      startDate: 'Fecha de inicio',
      endDate: 'Fecha de terminación',
      anticipoPercentage: 'Anticipo (%)',
      ivaRate: 'IVA (%)',
      retentionPercentage: 'Retenciones / fondo de garantía (%)',
      cincoAlMillar: '5 al millar SFP (%)',
      cincoAlMillarFixed: '0.5% (fijo por norma)',
      estimatePeriodicity: 'Periodicidad de estimaciones',
      periodicityMonthly: 'Mensual (una estimación por mes)',
      periodicityBiweekly: 'Quincenal (dos estimaciones por mes)',
      resident: 'Residente',
      superintendent: 'Superintendente',
      supervisor: 'Supervisor',
      contractor: 'Empresa contratista',
      contractorDerived: 'Se obtiene del superintendente seleccionado',
    },
    concepts: {
      hint: 'El monto del contrato se calculará como la suma de todos los conceptos.',
      add: 'Agregar concepto',
      empty: 'Agrega al menos un concepto al catálogo.',
      total: 'Monto total del contrato',
      columns: {
        specification: 'Especificación',
        description: 'Descripción',
        unit: 'Unidad',
        qty: 'Vol. contratado',
        unitPrice: 'P.U.',
        amount: 'Importe',
        remove: 'Quitar',
      },
      validation: {
        specRequired: 'Especificación requerida',
        descRequired: 'Descripción requerida',
        unitRequired: 'Unidad requerida',
        qtyPositive: 'Volumen debe ser > 0',
        pricePositive: 'P.U. debe ser > 0',
      },
    },
    schedule: {
      hint: 'Distribuye el volumen contratado de cada concepto entre los períodos. La suma por concepto debe igualar el volumen contratado.',
      ganttTitle: 'Vista previa del programa',
      periodHeader: 'P',
      total: 'Total',
      remaining: 'Restante',
      validation: {
        sumMismatch: 'La suma no coincide con el volumen contratado',
        allZero: 'Captura al menos un volumen en el programa',
      },
      allClear: 'El programa está completo. Todos los volúmenes cuadran.',
    },
    validation: {
      codeRequired: 'Ingresa la clave del contrato.',
      titleRequired: 'Ingresa el objeto del contrato.',
      datesRequired: 'El periodo del contrato es requerido.',
      endBeforeStart: 'La fecha de término debe ser posterior al inicio.',
      anticipoRange: 'El anticipo debe estar entre 0% y 100%.',
      ivaRange: 'El IVA debe estar entre 0% y 100%.',
      retentionRange: 'La retención debe estar entre 0% y 100%.',
      residentRequired:       'Selecciona un residente.',
      superintendentRequired: 'Selecciona un superintendente.',
      supervisorRequired:     'Selecciona un supervisor.',
      conceptsRequired: 'Agrega al menos un concepto.',
      scheduleRequired: 'Todos los conceptos deben tener fechas de programa.',
      scheduleOutOfRange: 'Hay fechas fuera del periodo del contrato.',
    },
    files: {
      title: 'Archivos iniciales del contrato',
      hint: 'Sube los documentos originales del contrato. Quedarán en la carpeta "Documentos del contrato".',
      dropzone: 'Arrastra archivos aquí o haz clic para seleccionar',
      dropzoneActive: 'Suelta los archivos…',
      uploading: 'Subiendo',
      uploaded: 'Subido',
      failed: 'Error',
      removeQueued: 'Quitar',
      finalize: 'Ir al contrato',
      skip: 'Omitir por ahora',
      uploadAll: 'Subir todos',
      sectionNote: 'Los archivos se suben una vez creado el contrato.',
    },
    submit: 'Crear contrato',
    submitting: 'Creando…',
  },
  conceptSections: {
    sectionHeader: 'Sección',
    noSection: 'Sin sección',
    subtotal: 'Subtotal sección',
    addSection: 'Agregar sección',
    removeSection: 'Quitar sección',
    specificationNumber: 'Especificación de sección',
    description: 'Descripción de la sección',
    period: 'Periodo de la sección',
    from: 'Del',
    to: 'Al',
    validation: {
      specRequired: 'Especificación requerida',
      descRequired: 'Descripción requerida',
      datesRequired: 'El periodo de la sección es requerido',
      endBeforeStart: 'La fecha de término debe ser posterior al inicio',
      startBeforeContract: 'El inicio de la sección no puede ser anterior al inicio del contrato',
      endAfterContract: 'El término de la sección no puede ser posterior al término del contrato',
      startBeforeSection: 'El inicio del concepto no puede ser anterior al inicio de su sección',
      endAfterSection: 'El término del concepto no puede ser posterior al término de su sección',
      conceptOutOfRange: 'Hay conceptos fuera del periodo de la sección',
    },
  },
  logNoteDetail: {
    folio: 'Folio',
    date: 'Fecha',
    author: 'Autor',
    body: 'Descripción',
    attachments: 'Anexos',
    attachmentsEmpty: 'Sin anexos.',
    sections: {
      content: 'Nota',
      signatures: 'Firmas',
    },
    status: {
      locked: 'Firmada y bloqueada',
      pending: 'Pendiente de firmas',
    },
    sign: 'Firmar nota',
    signHint: 'Una vez que los tres roles firmen, la nota quedará bloqueada e inmutable.',
    alreadySigned: 'Ya firmaste esta nota.',
  },
  logNote: {
    title: 'Bitácora',
    folio: 'Folio',
    dateTime: 'Fecha y hora',
    author: 'Autor',
    attachments: 'Anexos',
    attachmentsEmpty: 'Sin anexos.',
    empty: 'Sin notas en la bitácora.',
    sections: {
      content: 'Contenido',
      signatures: 'Firmas',
      fixedBody: 'Texto oficial',
      customBody: 'Observaciones adicionales',
    },
    status: {
      locked: 'Firmada',
      unlocked: 'Pendiente de firmas',
    },
    actions: { sign: 'Firmar nota' },
    lockedNotice: 'Esta nota quedará inmutable una vez que los tres roles la firmen.',
    signedNotice: 'Nota firmada por los tres roles. Inmutable.',
    openingRequired: 'Debes crear y firmar la nota de apertura antes de registrar otras notas.',
    openingUnsigned: 'La nota de apertura debe ser firmada por los tres roles antes de agregar otras notas.',
    newTitle: 'Nueva nota de bitácora',
    newOpeningTitle: 'Nota de apertura de bitácora',
    openingHint: 'Esta es la primera nota de la bitácora. El texto oficial se genera automáticamente con los datos del contrato.',
    categories: {
      apertura:        'Apertura de Bitácora',
      inicio_trabajos: 'Inicio de Trabajos',
      suspension:      'Suspensión de Trabajos',
      reanudacion:     'Reanudación de Trabajos',
      terminacion:     'Terminación de Trabajos',
      cierre:          'Cierre de Bitácora',
      estimaciones:    'Estimaciones / Conciliación de Volúmenes',
      conceptos_extra: 'Conceptos Extraordinarios / Volúmenes Excedentes',
      anticipos:       'Anticipos',
      retenciones:     'Retenciones / Sanciones',
      ordenes:         'Órdenes e Instrucciones',
      calidad:         'Control de Calidad y Laboratorio',
      planos:          'Planos y Especificaciones',
      seguridad:       'Seguridad e Higiene',
      personal:        'Designación / Cambio de Personal Técnico',
      minutas:         'Minutas de Trabajo / Visitas de Supervisión',
    },
    fields: {
      category: 'Categoría',
      title: 'Título',
      titlePlaceholder: 'Ej. Inicio de trazo y nivelación',
      customBody: 'Observaciones adicionales',
      customBodyPlaceholder: 'Agrega observaciones, instrucciones o cualquier información relevante…',
      residentCedula: 'Cédula profesional del Residente',
      superintendentCedula: 'Cédula profesional del Superintendente',
      cedulaPlaceholder: 'Ej. 1234567',
    },
    validation: {
      categoryRequired: 'Selecciona una categoría.',
      titleRequired: 'El título es requerido.',
    },
    search: {
      placeholder: 'Buscar en bitácora…',
      filterDate: 'Rango de fecha',
      filterCategory: 'Categoría',
      filterAuthor: 'Autor',
      noResults: 'Sin notas que coincidan con los filtros.',
      clearFilters: 'Limpiar filtros',
    },
    save: 'Crear nota',
    verMas: 'Ver más',
    verMenos: 'Ver menos',
  },
  schedulePage: {
    title: 'Programa de obra',
    summary: {
      physicalProgress: 'Avance físico',
      financialProgress: 'Avance financiero',
      plannedProgress: 'Avance planeado',
      behind: 'Conceptos rezagados',
      ahead: 'Conceptos adelantados',
      onTrack: 'Al corriente',
      done: 'Completados',
      overdue: 'Vencidos',
    },
    gantt: {
      title: 'Diagrama de Gantt',
      today: 'Hoy',
      legend: {
        done: 'Completado',
        executed: 'Ejecutado',
        ahead: 'Adelantado',
        on_track: 'Al corriente',
        behind: 'Rezagado',
        overdue: 'Vencido',
        future: 'Sin iniciar',
        remaining: 'Por ejecutar',
      },
    },
    sCurve: {
      title: 'Curva S',
      programmed: 'Programado',
      physical: 'Avance físico',
      financial: 'Avance financiero',
    },
    detail: {
      concept: 'Concepto',
      planned: 'Planeado',
      actual: 'Real',
      delta: 'Diferencia',
      status: 'Estado',
      start: 'Inicio',
      end: 'Término',
    },
    statusLabel: {
      done: 'Completado',
      ahead: 'Adelantado',
      on_track: 'Al corriente',
      behind: 'Rezagado',
      overdue: 'Vencido',
      future: 'Sin iniciar',
      not_started: 'Sin iniciar',
    },
  },
  files: {
    title: 'Explorador de archivos',
    folders: {
      contract: 'Documentos del contrato',
      evidence: 'Evidencias',
      payments: 'Comprobantes de pago',
      predefinedHint: 'Carpeta predefinida (no se puede renombrar ni eliminar)',
    },
    actions: {
      newFolder: 'Nueva carpeta',
      upload: 'Subir archivos',
      rename: 'Renombrar',
      delete: 'Eliminar',
      download: 'Descargar',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
    },
    upload: {
      dropHere: 'Arrastra archivos aquí o haz clic para seleccionar',
      dropActive: 'Suelta los archivos…',
      uploading: 'Subiendo',
      done: 'Listo',
      error: 'Error',
    },
    newFolderPlaceholder: 'Nombre de la carpeta',
    renamePlaceholder: 'Nuevo nombre',
    deleteFileConfirm: '¿Eliminar este archivo? Esta acción no se puede deshacer.',
    deleteFolderConfirm: '¿Eliminar esta carpeta y todo su contenido? Esta acción no se puede deshacer.',
    empty: 'Esta carpeta está vacía.',
    ownerOnly: 'Solo puedes eliminar archivos que tú subiste.',
    columns: {
      name: 'Nombre',
      size: 'Tamaño',
      uploadedBy: 'Subido por',
      uploadedAt: 'Fecha',
    },
  },
  financial: {
    title: 'Estado financiero',
    sections: {
      amounts: 'Monto contratado vs ejecutado',
      anticipo: 'Anticipo',
      unpaid: 'Estimaciones por pagar',
      breakdown: 'Distribución por sección / concepto',
    },
    amounts: {
      contracted: 'Monto contratado',
      executed: 'Ejecutado (aprobado)',
      paid: 'Pagado',
      balance: 'Saldo por pagar',
    },
    anticipo: {
      granted: 'Anticipo otorgado',
      amortized: 'Amortizado',
      remaining: 'Saldo de anticipo',
      percentage: 'Porcentaje',
    },
    unpaid: {
      empty: 'Sin estimaciones pendientes de pago.',
      number: 'Estimación No.',
      period: 'Periodo',
      amount: 'Total a pagar',
      markPaid: 'Marcar como pagada',
    },
    payModal: {
      title: 'Comprobante de pago',
      hint: 'Sube el comprobante de pago antes de confirmar. El archivo quedará en la carpeta "Comprobantes de pago".',
      dropzone: 'Arrastra el archivo aquí o haz clic para seleccionar',
      dropzoneActive: 'Suelta el archivo…',
      uploading: 'Subiendo…',
      uploaded: 'Archivo listo',
      change: 'Cambiar archivo',
      confirm: 'Confirmar pago',
      skip: 'Confirmar sin comprobante',
      optional: 'El comprobante es opcional pero se recomienda adjuntarlo.',
    },
    breakdown: {
      noSection: 'Sin sección',
      total: 'Total contratado',
    },
  },
  evidence: {
    title: 'Evidencias',
    new: 'Nueva evidencia',
    empty: 'Sin evidencias registradas.',
    fields: {
      title: 'Título',
      titlePlaceholder: 'Ej. Estado del terreno en zona norte',
      date: 'Fecha de la evidencia',
      body: 'Descripción',
      bodyPlaceholder: 'Describe la evidencia registrada…',
      files: 'Archivos adjuntos',
    },
    validation: {
      titleRequired: 'El título es requerido.',
      dateRequired: 'La fecha es requerida.',
      bodyRequired: 'La descripción es requerida.',
    },
    upload: {
      dropzone: 'Arrastra archivos o haz clic para adjuntar',
      dropzoneActive: 'Suelta los archivos…',
      uploading: 'Subiendo',
      done: 'Listo',
      error: 'Error al subir',
      remove: 'Quitar',
    },
    save: 'Guardar evidencia',
    columns: {
      title: 'Título',
      date: 'Fecha',
      author: 'Autor',
      files: 'Archivos',
    },
    detail: {
      files: 'Archivos adjuntos',
      noFiles: 'Sin archivos adjuntos.',
      download: 'Descargar',
    },
  },
  admin: {
    title: 'Administración',
    tabs: {
      users: 'Usuarios',
      corporations: 'Empresas contratistas',
      entities: 'Entidades',
    },
    users: {
      title: 'Usuarios',
      new: 'Nuevo usuario',
      empty: 'Sin usuarios registrados.',
      columns: {
        fullName: 'Nombre completo',
        username: 'Usuario',
        role: 'Rol',
        corporation: 'Empresa',
        status: 'Estado',
      },
      status: { active: 'Activo', inactive: 'Inactivo' },
      form: {
        title: 'Nuevo usuario',
        fullName: 'Nombre completo',
        fullNamePlaceholder: 'Ej. Juan Pérez',
        username: 'Nombre de usuario',
        usernamePlaceholder: 'Ej. jperez',
        password: 'Contraseña inicial',
        role: 'Rol',
        corporation: 'Empresa (para superintendente o supervisor)',
        entity: 'Entidad (para residente o finanzas)',
        cedula: 'Cédula profesional',
        cedulaPlaceholder: 'Ej. 1234567 (opcional)',
        save: 'Crear usuario',
      },
      validation: {
        fullNameRequired: 'El nombre completo es requerido.',
        usernameRequired: 'El nombre de usuario es requerido.',
        passwordRequired: 'La contraseña es requerida.',
        roleRequired: 'Selecciona un rol.',
        corporationRequired: 'El superintendente o supervisor debe tener una empresa asignada.',
        entityRequired: 'El residente y el usuario de finanzas deben pertenecer a una entidad.',
        usernameTaken: 'Este nombre de usuario ya existe.',
      },
    },
    corporations: {
      title: 'Empresas contratistas',
      new: 'Nueva empresa',
      empty: 'Sin empresas registradas.',
      columns: {
        name: 'Razón social',
        rfc: 'RFC',
        status: 'Estado',
      },
      form: {
        title: 'Nueva empresa',
        name: 'Razón social',
        namePlaceholder: 'Ej. Constructora del Valle, S.A. de C.V.',
        rfc: 'RFC',
        rfcPlaceholder: 'Ej. CVA120511AB3',
        save: 'Crear empresa',
      },
      validation: {
        nameRequired: 'La razón social es requerida.',
      },
    },
    entities: {
      title: 'Entidades',
      new: 'Nueva entidad',
      empty: 'Sin entidades registradas.',
      columns: {
        name: 'Nombre',
        username: 'Usuario',
        status: 'Estado',
      },
      form: {
        title: 'Nueva entidad',
        name: 'Nombre de la entidad',
        namePlaceholder: 'Ej. Dirección General de Obras Públicas',
        username: 'Nombre de usuario',
        usernamePlaceholder: 'Ej. dgop',
        password: 'Contraseña inicial',
        save: 'Crear entidad',
      },
      validation: {
        nameRequired: 'El nombre es requerido.',
        usernameRequired: 'El nombre de usuario es requerido.',
        passwordRequired: 'La contraseña es requerida.',
        usernameTaken: 'Este nombre de usuario ya existe.',
      },
    },
  },
} as const