// app/constants/strings.ts
/**
 * Centralized Spanish (es-MX) UI strings. Single place to edit copy; if real
 * i18n is ever needed, this becomes the default locale file. Not auto-imported
 * — import explicitly: `import { S } from '~/constants/strings'`.
 */
export const S = {
  app: {
    name: 'Gestor de Contratos',
    shortName: 'Contratos',
  },
  common: {
    save: 'Guardar',
    send: 'Enviar',
    saveAndSend: 'Guardar y enviar',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    back: 'Regresar',
    loading: 'Cargando…',
    search: 'Buscar',
    empty: 'Sin información',
    error: 'Ocurrió un error',
  },
  login: {
    title: 'Iniciar sesión',
    subtitle: 'Ingresa con tu usuario y contraseña',
    username: 'Usuario',
    password: 'Contraseña',
    submit: 'Entrar',
    usernameRequired: 'Ingresa tu usuario',
    passwordRequired: 'Ingresa tu contraseña',
    invalidCredentials: 'Usuario o contraseña incorrectos',
  },
  nav: {
    myContracts: 'Mis contratos',
    users: 'Usuarios',
    dashboard: 'Tablero',
    logbook: 'Bitácora',
    estimates: 'Estimaciones',
    schedule: 'Programa de obra',
    financial: 'Financiero',
    concepts: 'Catálogo de conceptos',
    evidence: 'Evidencias',
    files: 'Archivos',
    contract: 'Contrato',
    logout: 'Cerrar sesión',
  },
  roles: {
    admin: 'Administrador',
    resident: 'Residente',
    superintendent: 'Superintendente',
    supervisor: 'Supervisor',
    financial: 'Finanzas',
  },
  estimateStatus: {
    draft: 'Borrador',
    submitted: 'Enviada',
    with_notes: 'Con notas',
    rejected: 'Rechazada',
    approved: 'Aprobada',
    paid: 'Pagada',
  },
  agreementStatus: {
    draft: 'Borrador',
    submitted: 'Enviado',
    with_notes: 'Con notas',
    rejected: 'Rechazado',
    approved: 'Aprobado',
  },
  contractStatus: {
    active: 'Activo',
    closing: 'En cierre',
    closed: 'Cerrado',
  },
  dashboard: {
    title: 'Mis contratos',
    newContract: 'Nuevo contrato',
    empty: 'No tienes contratos asignados.',
    physicalProgress: 'Avance físico',
    executed: 'Ejercido',
    contracted: 'Contratado',
    alerts: 'Tienes alertas en este contrato',
  },
  contractDashboard: {
    balance: 'Balance',
    anticipo: 'Anticipo',
    overSchedule: 'Avance vs programa',
    programmed: 'Programado',
    actual: 'Real',
    physical: 'Físico',
    financial: 'Financiero',
    recentLogbook: 'Bitácora reciente',
    recentEstimates: 'Estimaciones recientes',
    viewAll: 'Ver todo',
    folio: 'Folio',
    noLogNotes: 'Sin notas de bitácora',
    noEstimates: 'Sin estimaciones',
    legend: 'Estados',
  },
  actions: {
    newLogNote: 'Nueva nota',
    uploadEvidence: 'Subir evidencia',
    conceptCatalog: 'Catálogo de conceptos',
    schedule: 'Programa de obra',
    files: 'Archivos',
  },
  conceptCatalog: {
    title: 'Catálogo de conceptos',
    empty: 'Este contrato no tiene conceptos registrados.',
    readonlyNotice: 'El catálogo es de solo lectura. Para modificar conceptos inicia un convenio modificatorio.',
    newAgreement: 'Nuevo convenio',
    columns: {
      specification: 'Especificación',
      description: 'Descripción',
      unit: 'Unidad',
      unitPrice: 'P.U.',
      contractedQty: 'Vol. contratado',
      contractedAmount: 'Importe contratado',
      executed: 'Vol. ejecutado',
      executedAmount: 'Importe ejecutado',
      remaining: 'Vol. por ejecutar',
    },
    search: 'Buscar concepto…',
    total: 'Total contratado',
  },
  estimateForm: {
    title: 'Nueva estimación',
    editTitlePrefix: 'Editar estimación',
    saveDraft: 'Guardar borrador',
    saveChanges: 'Guardar cambios',
    // Section anchors (one scrolling page)
    sections: {
      cover: 'Portada',
      concepts: 'Conceptos',
      summary: 'Resumen',
      attachments: 'Anexos',
    },
    // Cover
    cover: {
      contract: 'Contrato',
      object: 'Objeto del contrato',
      contractor: 'Contratista',
      number: 'Estimación No.',
      anticipo: 'Anticipo',
      periodFrom: 'Del',
      periodTo: 'Al',
      periodHint: 'Periodo que abarca la estimación',
    },
    // Concept selection (picker before the grid)
    conceptPicker: {
      label: 'Conceptos incluidos en esta estimación',
      hint: 'Selecciona los conceptos del catálogo que aplican. Solo los marcados aparecen en la cuadrícula.',
      addAll: 'Agregar todos',
      clearAll: 'Quitar todos',
      noMatch: 'Sin coincidencias',
      selected: 'seleccionados',
    },
    // Cell-color legend
    legend: {
      title: 'Colores',
      editable: 'Editable',
      calculated: 'Calculado',
      readonly: 'Solo lectura',
    },
    // 11 grid columns
    columns: {
      number: 'No.',
      specification: 'Especificación',
      description: 'Descripción',
      unit: 'Unidad',
      inProject: 'Vol. contratado',
      upToLast: 'Estimado anterior',
      inThisEstimate: 'En esta estimación',
      totalEstimated: 'Total estimado',
      toExecute: 'Por ejecutar',
      unitPrice: 'P.U.',
      totalAmount: 'Importe',
    },
    // Summary table 1 (concept rollup) + table 2 (calculations)
    summary: {
      conceptsTitle: 'Resumen por concepto',
      calculationsTitle: 'Cálculo de la estimación',
      subtotal: 'Subtotal',
      estimateAmount: 'Importe de la estimación',
      iva: 'IVA',
      estimateTotal: 'Total',
      anticipoAmortization: 'Amortización de anticipo',
      amortizationIva: 'IVA de la amortización',
      amortizationTotal: 'Total de amortización',
      retentions: 'Retenciones / fondo de garantía',
      cincoAlMillar: '5 al millar (SFP)',
      net: 'Total a pagar',
    },
    // Attachments
    attachments: {
      title: 'Anexos',
      linkHint: 'Vincula evidencias y notas de bitácora a esta estimación.',
      logNotes: 'Notas de bitácora',
      files: 'Archivos',
      logNotesEmpty: 'No hay notas de bitácora en este contrato.',
      filesEmpty: 'No hay archivos en este contrato.',
    },
    // Validation / empty states
    validation: {
      noConcepts: 'Este contrato no tiene conceptos en el catálogo.',
      periodRequired: 'Indica el periodo de la estimación.',
      periodOrder: 'La fecha de término no puede ser anterior a la de inicio.',
      noQuantities: 'Captura al menos un volumen para crear la estimación.',
      overContracted: 'Hay conceptos que superan el volumen contratado.',
      overRow: 'Supera el volumen contratado',
    },
  },
  estimateDetail: {
    titlePrefix: 'Estimación',
    period: 'Periodo',
    sections: {
      concepts: 'Conceptos',
      summary: 'Resumen',
      signatures: 'Firmas',
      history: 'Historial',
      attachments: 'Anexos',
    },
    signatures: {
      signed: 'Firmada',
      pending: 'Pendiente',
      signedAt: 'Firmó',
      unsigned: 'Sin firmar',
    },
    review: {
      title: 'Revisión',
    },
    attachmentsEmpty: 'Esta estimación no tiene anexos.',
    linkedLogNotes: 'Notas de bitácora vinculadas',
    evidence: 'Evidencias',
    // Workflow action buttons
    // NOTE: 'approve' is removed — signing IS approving. The last of the three
    // required signatures auto-transitions the estimate to 'approved'.
    actions: {
      edit: 'Editar',
      submit: 'Enviar a revisión',
      returnWithNotes: 'Devolver con notas',
      reject: 'Rechazar',
      markPaid: 'Marcar como pagada',
      sign: 'Firmar y aprobar',
    },
    // Note modal (return / reject)
    note: {
      returnTitle: 'Devolver con notas',
      rejectTitle: 'Rechazar estimación',
      label: 'Motivo',
      placeholder: 'Describe el motivo de la devolución o rechazo…',
      required: 'Escribe el motivo.',
    },
    // Highlighted banner for the latest returned/rejected note
    banner: {
      withNotes: 'Devuelta con notas',
      rejected: 'Rechazada',
    },
  },
  workflow: {
    created: 'Creada',
    submitted: 'Enviada a revisión',
    returned_with_notes: 'Devuelta con notas',
    rejected: 'Rechazada',
    approved: 'Aprobada',
    paid: 'Pagada',
    signed: 'Firmada',
    reopened: 'Reabierta',
  },
} as const